api:
  port: ":10001"
  timeout: 1000
database:
    postgres: 
      host: "localhost"
      port: "6432"
      dbname: "postgres"
      user: "postgres"
      password: "postgres"
      sslmode : "disable"
context:
  timeout: 10